export const Facts = [
    {id:'1', Message:'Birds are warm-blooded vertebrates that belong to the class Aves.'},
    {id:'2', Message:'The ostrich is the largest living bird and can reach heights of up to 9 feet (2.7 meters).'},
    {id:'3', Message:'The bee hummingbird is the smallest bird, with males weighing about 2.24 grams.'},
    {id:'4', Message:'Birds have feathers, which are modified scales, and they are unique to birds.'},
    {id:'5', Message:'Penguins are birds, even though they cannot fly. They are excellent swimmers instead.'},
    {id:'6', Message:'The oldest known bird fossils date back to the Late Jurassic period, over 150 million years ago.'},
    {id:'7', Message:'The kiwi bird is flightless and lays the largest egg in proportion to its body size of any bird species.'},
    {id:'8', Message:'The average body temperature of a bird is around 105 degrees Fahrenheit (40 degrees Celsius).'},
    {id:'9', Message:'Birds have a highly efficient respiratory system that allows them to extract more oxygen from the air than mammals.'},
    {id:'10', Message:'Some bird species, like parrots, can mimic human speech and other sounds.'},
    {id:'11', Message:'The American robin is the state bird of Connecticut, Michigan, and Wisconsin in the United States.'},
    {id:'12', Message:'The Atlantic puffin can dive underwater and swim using its wings to pursue prey.'},
    {id:'13', Message:'Birds have excellent color vision and can perceive ultraviolet light.'},
    {id:'14', Message:'The bar-tailed godwit holds the record for the longest non-stop flight by any bird, flying 7,258 miles (11,680 kilometers) in eight days.'},
    {id:'15', Message:'Birds have a unique adaptation called a crop, which is a muscular pouch in their digestive system where food can be stored before digestion.'},
    {id:'16', Message:'The national bird of India is the Indian peacock.'},
    {id:'17', Message:'Male birds are often more colorful and ornate than females because they use their plumage to attract mates.'},
    {id:'18', Message:'Owls can rotate their heads up to 270 degrees.'},
    {id:'19', Message:'The wandering albatross has the largest wingspan of any living bird, reaching up to 11.5 feet (3.5 meters).'},
    {id:'20', Message:"The Hoatzin bird, found in South America, has a unique digestive system that ferments its food like a cow's rumen."},
    {id:'21', Message:'Some bird species, like the African gray parrot, have demonstrated remarkable intelligence and problem-solving abilities.'},
    {id:'22', Message:'The call of a bald eagle, the national bird of the United States, is often referred to as a "scream."'},
    {id:'23', Message:"The Anna's hummingbird can hover mid-air and fly backward, reaching speeds of up to 30 miles per hour (48 kilometers per hour)."},
    {id:'24', Message:'The Australian lyrebird is known for its ability to mimic various sounds, including human speech, car alarms, and chainsaws.'},
    {id:'25', Message:'The Andean condor has the largest wingspan of any bird in the Western Hemisphere, measuring up to 10.5 feet (3.2 meters).'},
    {id:'26', Message:'Male emperor penguins are known for their exceptional parenting skills, as they incubate the eggs and care for the chicks while the females are at sea.'},
    {id:'27', Message:'The European starling was intentionally introduced to North America by Shakespeare enthusiasts in the late 19th century.'},
    {id:'28', Message:'Flamingos are born with gray feathers, and their vibrant pink color comes from the food they eat, which contains pigments called carotenoids.'},
    {id:'29', Message:'The hoatzin chick has claws on its wings, which it uses to climb trees before it is able to fly.'},
    {id:'30', Message:'The male superb lyrebird, found in Australia, has an elaborate courtship display that includes mimicking the calls of other birds and sounds from its environment.'},
    {id:'31', Message:'Many bird species, including swallows and arctic terns, undertake long-distance migrations each year.'},
    {id:'32', Message:'Some birds, like the African fish eagle and osprey, are excellent fishers and can catch fish in their talons while flying.'},
    {id:'33', Message:'The oilbird, found in South America, is the only bird known to use echolocation to navigate in complete darkness.'},
    {id:'34', Message:'The kakapo, a critically endangered parrot from New Zealand, is the heaviest parrot species in the world.'},
    {id:'35', Message:'The song of a canary is produced by a specialized voice box called a syrinx.'},
    {id:'36', Message:'The marabou stork, native to Africa, has the largest wingspan of any land bird, measuring up to 10.5 feet (3.2 meters).'},
    {id:'37', Message:'The male bowerbird constructs elaborate and highly decorated structures, called bowers, to attract females.'},
    {id:'38', Message:'The African grey crowned crane performs an elaborate courtship dance that involves leaping, bowing, and tossing grass in the air.'},
    {id:'39', Message:'The kookaburra, found in Australia, has a distinctive call that sounds like laughter.'},
    {id:'40', Message:"Many bird species, such as pigeons and homing birds, possess a remarkable ability to navigate using the Earth's magnetic field."},
    {id:'41', Message:'Some birds, like the northern flicker woodpecker, have tongues that wrap around the back of their skulls to cushion the impact of pecking.'},
    {id:'42', Message:'The kea, a parrot native to New Zealand, is known for its mischievous behavior and curiosity.'},
    {id:'43', Message:'The Eurasian magpie is one of the few non-mammal species that can recognize itself in a mirror.'},
    {id:'44', Message:"The male Anna's hummingbird produces a high-pitched sound during its dive displays, created by air passing through its tail feathers."},
    {id:'45', Message:'The kiwi bird is native to New Zealand and is the national symbol of the country.'},
    {id:'46', Message:'The male frigatebird, found in the Galapagos Islands, has a distinctive red throat pouch that it inflates during courtship displays.'},
    {id:'47', Message:'Some bird species, like the black-capped chickadee, can cache food by hiding it in various locations for future consumption.'},
    {id:'48', Message:'The peregrine falcon is the fastest bird in level flight, reaching speeds of up to 240 miles per hour (386 kilometers per hour) during its hunting dives.'},
    {id:'49', Message:'The male red-winged blackbird displays its brightly colored shoulder patches, or epaulets, to defend its territory.'},
    {id:'50', Message:'Birds are found on every continent and in every habitat, from the freezing Arctic to the deserts of Africa.'},
]